Fix: create-flag-location toegevoegd en op true gezet om de volgende foutmelding te voorkomen:
NotADirectoryError: Flag directory /tmp/migrate_flags does not exist. Please create it or set `create_flag_location` to True.